#pragma once

#define GHOSTSEAL_FIRMWARE_NAME "GhostSeal"
#define GHOSTSEAL_VERSION "0.1.0-fork"

#define GHOSTSEAL_UART_FIRST 1
#define GHOSTSEAL_QUIET_BOOT 1

#define GHOSTSEAL_START_AP_ON_BOOT 0
#define GHOSTSEAL_START_WEBUI_ON_BOOT 0
#define GHOSTSEAL_START_BLE_ADV_ON_BOOT 0

#define GHOSTSEAL_PI_CONTROL_MODE 1
#define GHOSTSEAL_REQUIRE_TOOL_ARM 1
#define GHOSTSEAL_DEFAULT_SERIAL_BAUD 115200